<template>
  <div class="about">
    <navBar></navBar>
      <img src="https://lh3.googleusercontent.com/Pmkbp95GKk8vMWCRlbWvPIdTbfwkFHeLOuuKIBSFDSK_8Dvd6wZ9welMxDg2kGDuhXdQ7wkec60tMprDxUHGdJUIhBrBctgKRLSE06hZ-Fukfh347wDmOsskFYT6nF0krtNCMs5Exg=w2400" style="height: 25vh; width: 13vw; position: fixed; top:20%; left:60%; transform: translate(-50%, -50%);" class="img-fluid">
          <p style="height: 20vh; width: 20vw; position: fixed; top:30%; left:40%; transform: translate(-50%, -50%);">
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras iaculis mauris urna. Pellentesque cursus ut eros at ultrices. Vestibulum vestibulum sem et euismod sollicitudin. Aenean at magna eu purus consectetur placerat et in lorem. Cras ut lacinia justo, sit amet volutpat dolor. Vestibulum eu tempor neque, sagittis dictum neque. Donec consequat varius dignissim. Nunc nec scelerisque enim, sit amet aliquam nisi. Cras eget faucibus ante. Nullam vulputate interdum tellus, ut aliquam ex ullamcorper sit amet. Nam metus arcu, tristique quis consectetur in, bibendum vulputate ligula. </p>
          <img src="https://lh3.googleusercontent.com/Pmkbp95GKk8vMWCRlbWvPIdTbfwkFHeLOuuKIBSFDSK_8Dvd6wZ9welMxDg2kGDuhXdQ7wkec60tMprDxUHGdJUIhBrBctgKRLSE06hZ-Fukfh347wDmOsskFYT6nF0krtNCMs5Exg=w2400" style="height: 25vh; width: 13vw; position: fixed; top:80%; left:25%; transform: translate(-50%, -50%);" class="img-fluid">
          <p style="height: 20vh; width: 20vw; position: fixed; top:65%; left:65%; transform: translate(-50%, -50%);">
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras iaculis mauris urna. Pellentesque cursus ut eros at ultrices. Vestibulum vestibulum sem et euismod sollicitudin. Aenean at magna eu purus consectetur placerat et in lorem. Cras ut lacinia justo, sit amet volutpat dolor. Vestibulum eu tempor neque, sagittis dictum neque. Donec consequat varius dignissim. Nunc nec scelerisque enim, sit amet aliquam nisi. Cras eget faucibus ante. Nullam vulputate interdum tellus, ut aliquam ex ullamcorper sit amet. Nam metus arcu, tristique quis consectetur in, bibendum vulputate ligula. </p>
  </div>
</template>